# Generated by Django 3.2.11 on 2025-09-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_uryo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_datetime', models.DateTimeField(verbose_name='観測日時')),
                ('item_type', models.CharField(max_length=50, verbose_name='項目種別')),
                ('unified_id', models.CharField(max_length=50, verbose_name='統一ID')),
                ('water_id', models.CharField(max_length=50, verbose_name='水水ID')),
                ('station_name', models.CharField(max_length=100, verbose_name='観測所名')),
                ('region_name', models.CharField(max_length=50, verbose_name='地方名')),
                ('water_system_name', models.CharField(max_length=50, verbose_name='水系名')),
                ('river_name', models.CharField(max_length=50, verbose_name='河川名')),
                ('manager', models.CharField(max_length=50, verbose_name='管理者')),
                ('management_type', models.CharField(max_length=50, verbose_name='管理区分')),
                ('observation_value', models.FloatField(blank=True, null=True, verbose_name='観測値')),
                ('neighbor1_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所1のID')),
                ('neighbor1_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所1の名称')),
                ('neighbor1_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所1の観測値')),
                ('neighbor2_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所2のID')),
                ('neighbor2_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所2の名称')),
                ('neighbor2_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所2の観測値')),
                ('neighbor3_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所3のID')),
                ('neighbor3_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所3の名称')),
                ('neighbor3_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所3の観測値')),
                ('neighbor4_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所4のID')),
                ('neighbor4_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所4の名称')),
                ('neighbor4_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所4の観測値')),
                ('neighbor5_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所5のID')),
                ('neighbor5_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所5の名称')),
                ('neighbor5_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所5の観測値')),
                ('neighbor6_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所6のID')),
                ('neighbor6_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所6の名称')),
                ('neighbor6_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所6の観測値')),
                ('neighbor7_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所7のID')),
                ('neighbor7_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所7の名称')),
                ('neighbor7_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所7の観測値')),
                ('neighbor8_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所8のID')),
                ('neighbor8_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所8の名称')),
                ('neighbor8_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所8の観測値')),
                ('neighbor9_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所9のID')),
                ('neighbor9_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所9の名称')),
                ('neighbor9_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所9の観測値')),
                ('neighbor10_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='近傍観測所10のID')),
                ('neighbor10_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='近傍観測所10の名称')),
                ('neighbor10_value', models.FloatField(blank=True, null=True, verbose_name='近傍観測所10の観測値')),
                ('idw_estimated_value', models.FloatField(blank=True, null=True, verbose_name='IDW推定値')),
                ('mesh_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='メッシュコード')),
                ('radar_rainfall', models.FloatField(blank=True, null=True, verbose_name='レーダ雨量')),
                ('idw_anomaly', models.FloatField(blank=True, null=True, verbose_name='IDW異常')),
                ('upper_limit', models.FloatField(blank=True, null=True, verbose_name='上限値')),
                ('missing_or_unreceived', models.BooleanField(default=False, verbose_name='欠測・未受信')),
                ('consecutive_abnormal_values', models.IntegerField(blank=True, null=True, verbose_name='連続する異常値')),
            ],
        ),
        migrations.CreateModel(
            name='WatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watching', models.BooleanField(default=False, verbose_name='監視中')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='最終チェック時刻')),
                ('processed_files_count', models.IntegerField(default=0, verbose_name='処理済みファイル数')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー数')),
            ],
            options={
                'verbose_name': '監視状態',
                'verbose_name_plural': '監視状態',
            },
        ),
    ]
