# Generated by Django 3.2.11 on 2025-09-17 06:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MS_Kansokujo_Update',
            fields=[
                ('KansokujoCD', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='観測所コード')),
                ('ShubetsuCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='観測所種別コード')),
                ('KansokujoCD2', models.CharField(max_length=20, verbose_name='観測所コード(川防用)')),
                ('KansokujoName', app.models.CustomTextField(verbose_name='観測所名')),
                ('KansokujoYomi', app.models.CustomTextField(blank=True, null=True, verbose_name='観測所読み')),
                ('Shozaichi', app.models.CustomTextField(blank=True, null=True, verbose_name='所在地')),
                ('CenterCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='センター(運用課)コード')),
                ('ShozokuCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属区分コード')),
                ('KanriCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='管理区分コード')),
                ('KenCD', models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県コード')),
                ('JimushoCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='事務所コード')),
                ('JimushoCD2', models.CharField(blank=True, max_length=20, null=True, verbose_name='事務所コード2')),
                ('SuikeiCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='水系コード(入力用)')),
                ('SuikeiCD2', models.CharField(blank=True, max_length=20, null=True, verbose_name='水系コード(出力用)')),
                ('KasenCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='河川コード(入力用)')),
                ('KasenCD2', models.CharField(blank=True, max_length=20, null=True, verbose_name='河川コード(出力用)')),
                ('Hyokou', app.models.CustomTextField(blank=True, null=True, verbose_name='標高')),
                ('Ido', app.models.CustomTextField(blank=True, null=True, verbose_name='緯度')),
                ('Keido', app.models.CustomTextField(blank=True, null=True, verbose_name='経度')),
                ('KijunFLG', models.BooleanField(default=False, verbose_name='基準観測所フラグ')),
                ('TenyuryokuFLG', models.BooleanField(default=False, verbose_name='手入力フラグ')),
                ('StartYMD', models.DateField(blank=True, null=True, verbose_name='観測開始日')),
                ('EndYMD', models.DateField(blank=True, null=True, verbose_name='観測終了日')),
                ('HyoujiNo', models.IntegerField(blank=True, null=True, verbose_name='画面表示順')),
                ('ShutsuryokuNo', models.IntegerField(blank=True, null=True, verbose_name='帳票出力順')),
                ('K_GroupCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='一斉欠測グループコード')),
                ('S_GroupCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='出力観測所グループコード')),
                ('SuiiShuuchiFLG', models.BooleanField(default=False, verbose_name='水位周知フラグ')),
                ('KansokuKikiCD', models.CharField(blank=True, max_length=20, null=True, verbose_name='観測機器コード')),
                ('KansokuKikiYMD', models.CharField(blank=True, max_length=20, null=True, verbose_name='観測機器更新日')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='レコード作成日時')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='レコード更新日時')),
                ('DelFlg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('DblFlg', models.BooleanField(default=False, verbose_name='重複フラグ')),
                ('K_Time', models.CharField(blank=True, max_length=20, null=True, verbose_name='欠測継続時間')),
                ('Kijunchi', models.CharField(blank=True, max_length=20, null=True, verbose_name='基準値')),
                ('Jougenchi', models.CharField(blank=True, max_length=20, null=True, verbose_name='上限値')),
                ('Kagenchi', models.CharField(blank=True, max_length=20, null=True, verbose_name='下限値')),
                ('Hendouryou', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='変動量')),
                ('TempFile01', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル1')),
                ('TempFile02', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル2')),
                ('TempFile03', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル3')),
                ('TempFile04', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル4')),
                ('TempFile05', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル5')),
                ('TempFile06', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル6')),
                ('TempFile07', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル7')),
                ('TempFile08', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル8')),
                ('TempFile09', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル9')),
                ('TempFile10', models.ImageField(blank=True, null=True, upload_to='kansokujo_photos/', verbose_name='添付ファイル10')),
            ],
            options={
                'verbose_name': '観測所更新マスタ(MS_Kansokujo_Update)',
                'verbose_name_plural': '観測所更新マスタ(MS_Kansokujo_Update)',
                'db_table': 'MS_Kansokujo_Update',
                'ordering': ['KansokujoCD'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('file_size', models.BigIntegerField(verbose_name='ファイルサイズ')),
                ('file_hash', models.CharField(max_length=64, verbose_name='ファイルハッシュ')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='処理日時')),
                ('records_count', models.IntegerField(default=0, verbose_name='レコード数')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', 'エラー'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='処理状態')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
            ],
            options={
                'verbose_name': '処理済みファイル',
                'verbose_name_plural': '処理済みファイル',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watching', models.BooleanField(default=False, verbose_name='監視中')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='最終チェック時刻')),
                ('processed_files_count', models.IntegerField(default=0, verbose_name='処理済みファイル数')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー数')),
            ],
            options={
                'verbose_name': '監視状態',
                'verbose_name_plural': '監視状態',
            },
        ),
    ]
