# Generated by Django 3.2.11 on 2025-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('file_size', models.BigIntegerField(verbose_name='ファイルサイズ')),
                ('file_hash', models.CharField(max_length=64, verbose_name='ファイルハッシュ')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='処理日時')),
                ('records_count', models.IntegerField(default=0, verbose_name='レコード数')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', 'エラー'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='処理状態')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
            ],
            options={
                'verbose_name': '処理済みファイル',
                'verbose_name_plural': '処理済みファイル',
                'ordering': ['-processed_at'],
            },
        ),
    ]
