version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    command: >
      python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
      - ./csv_input:/app/csv_input
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ijouchi_db
      DB_USER: frics
      DB_PASSWORD: frics-8080
      TZ: Asia/Tokyo

  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ijouchi_db
      MYSQL_USER: frics
      MYSQL_PASSWORD: frics-8080
      MYSQL_ROOT_HOST: '%'
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --skip-name-resolve
      --bind-address=0.0.0.0
    ports:
      - "3308:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql