version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ijouchi_db
      - DB_USER=frics
      - DB_PASSWORD=frics-8080
      - TZ=Asia/Tokyo

  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ijouchi_db
      MYSQL_USER: frics
      MYSQL_PASSWORD: frics-8080
      TZ: Asia/Tokyo
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
