# config.ini

[mail_info]
FROM_ADDRESS = 4kf4k7@bma.biglobe.ne.jp
MY_PASSWORD = xbx8da5y
; to_email = k-watanabe@dpsol.co.jp,h-ohmura@dpsol.co.jp
to_email = t-kimura@dpsol.co.jp
from_email = 4kf4k7@bma.biglobe.ne.jp
filepath = /Users/CSV/

[File_Path]
filepath = ./CSV/

[FileName]
FileName = YYMMDD

[Mail_sbj]
Mail_subject = 異常値検出ツール：基準値超過結果
Mail_message = 異常値検出ツールで抽出された検出結果及び異常値等データベース登録状況です。

#*****************読み込み方法
#import configparser
#ini = configparser.ConfigParser()
#ini.read('./config.ini', 'UTF-8')
#print(ini['db_info']['user'])
