# config.ini

[mail_info]
FROM_ADDRESS = 4kf4k7@bma.biglobe.ne.jp
MY_PASSWORD = xbx8da5y
; to_email = k-watanabe@dpsol.co.jp,h-ohmura@dpsol.co.jp
to_email = t-kimura@dpsol.co.jp
from_email = 4kf4k7@bma.biglobe.ne.jp
filepath = /app/media  

[File_Path]
zip_filepath = /app/media/zip  
; ZIPファイルをここに保存
excel_filepath = /app/media/excel  
; Excelファイルをここに保存

[FileName]
FileName = YYMMDD

[Mail_sbj]
Mail_subject = 異常値検出ツール：基準値超過結果
Mail_message = 異常値検出ツールで抽出された検出結果及び異常値等データベース登録状況です。

; 添付ファイル(調査書)アップロード先情報
[upload_info]
Kanshi_Path = /home/surveydb/SurveyDB/media/Temp/調査書/監視者/
Handan_Path = /home/surveydb/SurveyDB/media/Temp/調査書/判断者/
Host_Server = 192.168.99.193
Host_User = surveydb
Host_Pass = frics-8080

#*****************読み込み方法
#import configparser
#ini = configparser.ConfigParser()
#ini.read('./config.ini', 'UTF-8')
#print(ini['db_info']['user'])
